name: Trigger Netlify Build at Midnight
on:
  workflow_dispatch:
  schedule:
    # Every day at midnight PDT - default TZ is UTC
    - cron: '0 7 * * *'
jobs:
  build:
    name: Netlify Midnight Cron
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_HOOK_ID }}
